; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S -ipsccp %s | FileCheck %s

@global = external addrspace(1) global i32, align 4

; Function Attrs: readonly
define void @hoge() #0 {
; CHECK-LABEL: @hoge(
; CHECK-NEXT:  bb:
; CHECK-NEXT:    br label [[BB8:%.*]]
; CHECK:       bb1:
; CHECK-NEXT:    br i1 true, label [[BB2:%.*]], label [[BB1:%.*]]
; CHECK:       bb2:
; CHECK-NEXT:    [[TMP3:%.*]] = load i16, i16 addrspace(1)* bitcast (i32 addrspace(1)* @global to i16 addrspace(1)*), align 2
; CHECK-NEXT:    [[TMP4:%.*]] = icmp eq i16 [[TMP3]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = select i1 [[TMP4]], i16 addrspace(1)* bitcast (i32 addrspace(1)* @global to i16 addrspace(1)*), i16 addrspace(1)* bitcast (i32 addrspace(1)* @global to i16 addrspace(1)*)
; CHECK-NEXT:    br label [[BB8]]
; CHECK:       bb8:
; CHECK-NEXT:    br label [[BB1]]
;
bb:
  br label %bb8

bb1:                                              ; preds = %bb8, %bb1
  %tmp = icmp eq i32 0, 0
  br i1 %tmp, label %bb2, label %bb1

bb2:                                              ; preds = %bb1
  %tmp3 = load i16, i16 addrspace(1)* %tmp9, align 2
  %tmp4 = icmp eq i16 %tmp3, 0
  %tmp5 = select i1 %tmp4, i16 addrspace(1)* %tmp10, i16 addrspace(1)* %tmp9
  %tmp6 = select i1 undef, i16 addrspace(1)* bitcast (i32 addrspace(1)* @global to i16 addrspace(1)*), i16 addrspace(1)* %tmp9
  %tmp7 = select i1 undef, i16 addrspace(1)* bitcast (i32 addrspace(1)* @global to i16 addrspace(1)*), i16 addrspace(1)* %tmp10
  br label %bb8

bb8:                                              ; preds = %bb2, %bb
  %tmp9 = phi i16 addrspace(1)* [ undef, %bb ], [ %tmp6, %bb2 ]
  %tmp10 = phi i16 addrspace(1)* [ undef, %bb ], [ %tmp7, %bb2 ]
  br label %bb1
}

attributes #0 = { readonly }
